### ISSUE TITLE
Graphical Issue - Wheels along bottom spin the wrong way

### ISSUE THREAD

**Issue by MattcTrent** [sEdutech/BaseGame#26]
Description: the wheels along the bottom of the screen spin the opposite direction to the tracks on the bottom of the screen

Steps: Start the game and the circles spin the wrong direction

Device: PC & Samsung S5

**Comment by Flave229** [comment]
![image](http://i.imgur.com/NWksiOz.gif)

**Comment by kieran154** [comment]
Sorted thanks
