### ISSUE TITLE
Police runs straight to player once out of bounds

### ISSUE THREAD

**Issue by Flave229** [sEdutech/BaseGame#31]
**Description:**
If the player does so well as to cause the policeman to exit the bounds of the screen to the left, the policeman then seems to randomly decide to sprint directly at the player without stopping.

**To replicate:** 
Start the game, avoid obstacles and keep delivering newspapers to cause the policeman to go left, until he is outside of the viewable bounds of the screen. Continue to keep the policeman out of sight, and he should soon sprint out and catch the player instantly.

**Suggestion:**
A possible solution would to put a maximum distance that the policeman can be at, so he always remains on the screen. Even if the player does extraordinarily well, the policeman will never go so far left as to disappear off the screen. 

**Occurance:**
Occurs 100% of the time, provided you can keep the policeman to the left.

**Device:** 
Android, Nexus 5

**Image:**
![image](http://i.imgur.com/fRToE9P.gifm)

**Comment by DeadManIV** [comment]
Issue resolved.
