### ISSUE TITLE
Occasionally, Policeman will not back away on successful paper delivery 

### ISSUE THREAD

**Issue by Flave229** [sEdutech/BaseGame#32]
**Description:**
Occasionally, the policeman will not back up when a paper has been delivered. This seems to only happen if the policeman is currently moving towards the player.

**To replicate:** 
Attempt to get a paper delivered at a door at the exact same time the policeman is moving towards the player.

**Suggestion:**
Perhaps queuing up actions for the policeman, or simply overriding previous actions, would fix this issue.

**Occurance:**
Occurs 100% of the time, if newspaper delivered within the time-frame that the policeman moves forward.

**Device:** 
Android, Nexus 5

**Image:**
![image](http://i.imgur.com/bJq8Nj9.gifm)

**Comment by kieran154** [comment]
Sorted thanks
