### ISSUE TITLE
Upon committing two bad actions, Policeman only moves forward one

### ISSUE THREAD

**Issue by Flave229** [sEdutech/BaseGame#33]
**Description:**
When the player does two 'bad' actions, such as colliding with a fire hydrant and smashing a window, at the same time, the policeman only moves forward one 'pace'.

**To replicate:** 
Start the game, then collide with an object as you smash a window with a news paper.

**Occurance:**
Occurs 100% of the time, if two bad actions successfully committed. 

**Suggestion:**
Queuing actions may be a good way to handle this. 

**Device:** 
Android, Nexus 5

**Image:**
![image](http://i.imgur.com/dWTtfXb.gifm)

**Comment by kieran154** [comment]
Sorted thanks
