### ISSUE TITLE
Gameplay Bug: Seagull won’t attack the player. 

### ISSUE THREAD

**Issue by JamesEdgerton1995** [sEdutech/BaseGame#34]
The seagull will not “attack” the player, and simply hover from right to left.

Steps to Reproduce: Encountered after playing for extended periods of time, Or when multiple objects spawn at the same time.

Platform: Windows

Occurrence
100% Given long enough playtime. 
5% On personal ability to reach a point where this occurs 

![1220om](https://cloud.githubusercontent.com/assets/15675235/14325111/b7067e52-fc1f-11e5-916f-f96906e364ec.gif)

**Comment by Flave229** [comment]
The seagull backs off if hit with a newspaper - Could you have accidentally hit it?

**Comment by ash-jones** [comment]
This is a known issue, its actually because the bird has a small chance to spawn as a special enemy that hasn't been implemented yet and jimmy used the bird as temporary art.

**Comment by DeadManIV** [comment]
This isn't a bug, it's the UFO enemy (sprite change coming soon)
