### ISSUE TITLE
Score Not Displaying

### ISSUE THREAD

**Issue by MegaRGJ** [sEdutech/BaseGame#35]
Description: Score is not displaying on the pc and LG G4.

Reproduce: Loading game normally.

Specs: Windows 10, Intel i7-6700HQ 2.6GHz, 8 GB, 64-bit OS. and LG G4.

![scorebug](https://cloud.githubusercontent.com/assets/15675190/14349637/3584bd4c-fcbc-11e5-8308-d6269a3ea48c.jpg)

**Comment by GamesB2** [comment]
This is a known issue, score is not yet implemented and the text is a placeholder.
